# Backend: Conexión con tu repositorio de GitHub
backend:
  name: github
  repo: pepsend/catalogo # ¡Listo para ti!
  branch: main 

# Media: Dónde se guardarán las imágenes que subas
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

# Collections: Define el tipo de contenido que gestionarás (tus juegos)
collections:
  - name: "juegos"
    label: "Juegos"
    folder: "_juegos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nombre del Juego", name: "nombre", widget: "string"}
      - {label: "Precio", name: "precio", widget: "string"}
      - {label: "Portada del Juego", name: "portada", widget: "image"}
