backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"         # Donde el CMS subir치 las im치genes
public_folder: "/assets/uploads"       # C칩mo accedemos a ellas desde la web

collections:
  - name: "juegos"
    label: "Juegos"
    folder: "_juegos"                  # Carpeta de tu colecci칩n real
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "nombre", widget: "string" }
      - { label: "Precio", name: "precio", widget: "string" }
      - { label: "Caratula", name: "caratula", widget: "image" }
